# Generated by Django 3.2.4 on 2021-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(default='ENGLISH/EN-IN', help_text='enter the valid language sign and word, that will be understandable easily', max_length=100),
        ),
    ]
